name = "abuseipdb"
main = "cloudflare-worker.js"
compatibility_date = "2024-06-08"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "abuseipdb"
routes = []
# If you have a custom domain, you can add:
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Preview environment - same worker, accessed via query param or header
[env.preview]
name = "abuseipdb"
routes = []
# If you have a custom domain, you can add:
# routes = [
#   { pattern = "preview.api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Environment variables can be set per environment
[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"

# Environment variables (these will be set via GitHub Actions secrets)
# [vars]
# ENVIRONMENT = "production"

# KV bindings (if needed in the future)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# R2 bindings (if needed in the future)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Durable Objects (if needed in the future)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Custom domains (configure after deployment)
# [env.production]
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
