name: Security Scan

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop", "feature/*" ]
  schedule:
    - cron: '0 18 * * 0'  # Weekly on Sundays at 6 PM UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run .NET Security Scan
      run: |
        # Install dotnet security scan tool
        dotnet tool install --global security-scan --version 5.6.7 || true
        
        # Run security scan
        security-scan --project=Albatross.sln --export=security-scan-results.sarif || true

    - name: Upload Security Scan results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: security-scan-results.sarif
        category: dotnet-security-scan
      continue-on-error: true

    - name: Setup Node.js for npm audit
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run npm audit
      run: |
        if [ -f package.json ]; then
          npm audit --audit-level=moderate
        fi
      continue-on-error: true
